[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[cutefish-appmotor]
source = "github"
github = "cutefishos/appmotor"
use_latest_tag = true

[cutefish-calculator]
source = "github"
github = "cutefishos/calculator"
use_latest_tag = true

[cutefish-dock]
source = "github"
github = "cutefishos/dock"
use_latest_tag = true

[cutefish-filemanager]
source = "github"
github = "cutefishos/filemanager"
use_latest_tag = true

[cutefish-gtk-themes]
source = "github"
github = "cutefishos/gtk-themes"
use_latest_tag = true

[cutefish-icons]
source = "github"
github = "cutefishos/icons"
use_latest_tag = true

[cutefish-kwin-plugins]
source = "github"
github = "cutefishos/kwin-plugins"
use_latest_tag = true

[cutefish-launcher]
source = "github"
github = "cutefishos/launcher"
use_latest_tag = true

[cutefish-qt-plugins]
source = "github"
github = "cutefishos/qt-plugins"
use_latest_tag = true

[cutefish-screenlocker]
source = "github"
github = "cutefishos/screenlocker"
use_latest_tag = true

[cutefish-screenshot]
source = "github"
github = "cutefishos/screenshot"
use_latest_tag = true

[cutefish-sddm-theme]
source = "github"
github = "cutefishos/sddm-theme"
use_latest_tag = true

[cutefish-settings]
source = "github"
github = "cutefishos/settings"
use_latest_tag = true

[cutefish-statusbar]
source = "github"
github = "cutefishos/statusbar"
use_latest_tag = true

[cutefish-terminal]
source = "github"
github = "cutefishos/terminal"
use_latest_tag = true

[cutefish-texteditor]
source = "github"
github = "cutefishos/texteditor"
use_latest_tag = true

[cutefish-videoplaper]
source = "github"
github = "cutefishos/videoplayer"
use_latest_tag = true

[cutefish-wallpapers]
source = "github"
github = "cutefishos/wallpapers"
use_latest_tag = true

[cutefish-core]
source = "github"
github = "cutefishos/core"
use_latest_tag = true

[fishiui]
source = "github"
github = "cutefishos/fishui"
use_latest_tag = true

[libcutefish]
source = "github"
github = "cutefishos/libcutefish"
use_latest_tag = true
